"""Symbolic ground truth for the Bose-Marletto-Vedral (BMV) protocol.

The BMV protocol (Bose et al. 2017, "Spin Entanglement Witness for Quantum
Gravity"; Marletto & Vedral 2017) tests whether the gravitational field can
entangle two initially independent, spatially superposed test masses. Two
masses ``m1`` and ``m2``, separated by a mean distance ``d``, are each split
into a spatial superposition of two paths offset by ``delta_x`` and held for
a time ``T``. The four path combinations (near/near, far/far, near/far,
far/near) accumulate different Newtonian gravitational phases; the
difference between the "correlated" and "anti-correlated" branches is the
relative phase that seeds entanglement between the two mass qubits.

If gravity were a strictly classical, LOCC-type mediator, no entanglement
could be generated between the two initially unentangled quantum systems.
Observing a nonzero entanglement witness (equivalently, a nonzero relative
phase) is therefore evidence that the gravitational interaction itself must
carry quantum degrees of freedom -- this is the "classical vs. quantum
gravity" discriminator referenced throughout this example.

This module derives the leading-order relative phase symbolically (via a
Taylor expansion of the Newtonian potential -- the "cross-propagator" term
that couples the two mass superpositions) rather than hard-coding the
closed-form result, so it can serve as an independently-checkable oracle for
the evolutionary search in ``evolve.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

import sympy as sp

# Symbolic parameters. All are physically positive quantities.
G, m1, m2, delta_x, d, T, hbar = sp.symbols("G m1 m2 delta_x d T hbar", positive=True)

_PARAM_SYMBOLS = {"G": G, "m1": m1, "m2": m2, "delta_x": delta_x, "d": d, "T": T, "hbar": hbar}

# Expected power-law exponents of the leading-order relative phase, used to
# grade candidate programs on whether they recovered the correct scaling
# law rather than merely curve-fitting a handful of parameter points.
EXPECTED_SCALING_EXPONENTS = {
    "G": 1,
    "m1": 1,
    "m2": 1,
    "delta_x": 2,
    "T": 1,
    "d": -3,
    "hbar": -1,
}

# Real-world constants (SI units).
G_SI = 6.6743e-11
HBAR_SI = 1.054571817e-34


def newtonian_potential(r: sp.Expr) -> sp.Expr:
    """Newtonian gravitational potential energy between m1 and m2 at separation r."""
    return -G * m1 * m2 / r


@lru_cache(maxsize=1)
def relative_phase_symbolic(order: int = 4) -> sp.Expr:
    """Derive the leading-order BMV relative phase via Taylor expansion.

    The interaction-picture phase accumulated by each path is
    ``phi_branch = -(1/hbar) * V(r_branch) * T`` (constant potential during
    the hold time, the "static" approximation used in the original BMV
    proposal). The witness-relevant combination is the difference between
    the correlated branches (masses displaced together, separation
    unchanged at ``d``) and the anti-correlated branches (separation
    ``d -+ delta_x``):

        delta_phi = -(T/hbar) * [V(d - delta_x) + V(d + delta_x) - 2*V(d)]

    Odd powers of ``delta_x`` cancel by symmetry, so the leading
    contribution is the quadratic ("cross-propagator") term.
    """
    cross_term = newtonian_potential(d - delta_x) + newtonian_potential(d + delta_x) - 2 * newtonian_potential(d)
    series = sp.series(cross_term, delta_x, 0, order).removeO()
    leading = series.coeff(delta_x, 2) * delta_x**2
    phi = sp.simplify(-(T / hbar) * leading)
    return phi


def scaling_exponents(expr: sp.Expr) -> dict[str, sp.Rational]:
    """Extract the power-law exponent of each physical parameter in a monomial expression."""
    powers = sp.sympify(expr).as_powers_dict()
    exponents: dict[str, sp.Rational] = {}
    for name, sym in _PARAM_SYMBOLS.items():
        exponents[name] = powers.get(sym, sp.Integer(0))
    return exponents


def concurrence_symbolic(phi: sp.Expr) -> sp.Expr:
    """Entanglement (concurrence) generated by a relative phase gate on a product state.

    Applying a relative phase ``phi`` between the correlated and
    anti-correlated branches of two path qubits initially in ``|+>|+>``
    produces a state whose concurrence is ``|sin(phi)|`` -- zero for
    ``phi = 0`` (no entanglement, consistent with a non-interacting or
    purely classical mediator) and maximal for ``phi = pi/2``.
    """
    return sp.Abs(sp.sin(phi))


@dataclass(frozen=True)
class ReferenceResult:
    phase: float
    concurrence: float


def numeric_result(params: dict[str, float]) -> ReferenceResult:
    """Evaluate the reference phase and concurrence for a numeric parameter set."""
    phi_expr = relative_phase_symbolic()
    subs = {_PARAM_SYMBOLS[name]: value for name, value in params.items()}
    phi_val = float(phi_expr.subs(subs))
    conc_val = float(sp.Abs(sp.sin(phi_val)))
    return ReferenceResult(phase=phi_val, concurrence=conc_val)
